# Cloud Run Deployment Configuration (GCP)
# gcloud run deploy early-warning-api --source . --region us-central1

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: early-warning-api
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '1'
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/cpu-throttling: 'false'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/early-warning-api:latest
        ports:
        - name: http1
          containerPort: 8000
        env:
        - name: ENV
          value: "production"
        - name: MLFLOW_TRACKING_URI
          value: "https://mlflow.example.com"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          limits:
            cpu: '2'
            memory: 4Gi
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
  traffic:
  - percent: 100
    latestRevision: true
